### PR TITLE
Upgrade styled-jss version and fix DifferentBlocks

### PR DESCRIPTION
**Pull request by lttb**

### CODE REVIEW

**Comment by tuchk4** [comment]
@lttb deployed to https://tuchk4.github.io/css-in-js-app/

**Comment by lttb** [comment]
@tuchk4 Great, thanks!

**Comment by tuchk4** [comment]
@lttb 
seems something wrong with colors after re-render
wrong colors

**Comment by lttb** [comment]
@tuchk4 I see, thanks. looking for a problem

**Pull request merged**
